export interface CategoryConfig {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  popularSkills: string[];
}

export const CATEGORIES: CategoryConfig[] = [
  {
    id: "tech",
    name: "Technology",
    slug: "technology",
    description: "Web, mobile, databases, scripting & AI implementations",
    icon: "Code",
    popularSkills: ["React", "Next.js", "Python", "Full-Stack", "Flutter", "Node.js", "APIs"],
  },
  {
    id: "design",
    name: "Design",
    slug: "design",
    description: "UI/UX, wireframes, design systems & graphic design",
    icon: "Layout",
    popularSkills: ["Figma", "UI/UX", "Mobile UI", "Design Systems", "Prototyping"],
  },
  {
    id: "art",
    name: "Art",
    slug: "art",
    description: "Digital art, portraits, sketches & creative illustrations",
    icon: "Palette",
    popularSkills: ["Digital Painting", "Portrait Art", "Illustration", "Caricatures"],
  },
  {
    id: "photo",
    name: "Photography",
    slug: "photography",
    description: "College fest, product, portrait & event coverage",
    icon: "Camera",
    popularSkills: ["Event Coverage", "Portrait", "Lightroom", "College Fests"],
  },
  {
    id: "video",
    name: "Video",
    slug: "video",
    description: "Reels editing, documentary, trailers & color grading",
    icon: "Video",
    popularSkills: ["Reels", "Premiere Pro", "After Effects", "Color Grading"],
  },
  {
    id: "marketing",
    name: "Marketing",
    slug: "marketing",
    description: "Social media campaigns, campus outreach & growth",
    icon: "TrendingUp",
    popularSkills: ["Instagram Growth", "Campus Marketing", "Campaigns", "Copywriting"],
  },
  {
    id: "events",
    name: "Events",
    slug: "events",
    description: "Fest planning, volunteer coordination & stage execution",
    icon: "Calendar",
    popularSkills: ["Fest Planning", "Logistics", "Stage Management", "Anchoring"],
  },
  {
    id: "decoration",
    name: "Decoration",
    slug: "decoration",
    description: "Theme stage design, backdrop setup & origami craft",
    icon: "Sparkles",
    popularSkills: ["Stage Backdrops", "Origami", "Fest Decoration", "Floral Setups"],
  },
  {
    id: "tutoring",
    name: "Tutoring",
    slug: "tutoring",
    description: "Mathematics, Physics, Coding & competitive exam prep",
    icon: "BookOpen",
    popularSkills: ["JEE Physics", "Calculus", "DSA Tutoring", "Linear Algebra"],
  },
  {
    id: "content",
    name: "Content",
    slug: "content",
    description: "Technical blogs, SEO copywriting, documentation & pitches",
    icon: "FileText",
    popularSkills: ["SEO Blogs", "Technical Writing", "Pitch Decks", "Case Studies"],
  },
  {
    id: "music",
    name: "Music",
    slug: "music",
    description: "Jingle creation, background scores, vocals & mixing",
    icon: "Music",
    popularSkills: ["Jingles", "Audio Mixing", "Guitar Vocals", "Background Scores"],
  },
  {
    id: "crafts",
    name: "Crafts",
    slug: "crafts",
    description: "Custom exhibition models, 3D prototypes & DIY physical work",
    icon: "Layers",
    popularSkills: ["3D Models", "Exhibition Stalls", "Clay Craft", "Architectural Models"],
  },
];

export const SITE_CONFIG = {
  name: "SkillSetu",
  tagline: "Skills that connect. Opportunities that grow.",
  description: "A verified Indian student marketplace connecting skilled college talent with startups, organizations, and clients with protected payments.",
  url: "https://skillsetu.in",
  platformFeeRate: 0.05, // 5% client convenience fee
  supportEmail: "support@skillsetu.in",
  subscriptionPlans: [
    {
      id: "free" as const,
      name: "Free Student",
      badge: "Forever Free",
      tagline: "Basic plan for every verified college student getting started.",
      monthlyPrice: 0,
      yearlyMonthlyEquivalent: 0,
      yearlyTotalPrice: 0,
      commissionRate: "5% platform fee",
      listingsLimit: "2 listings",
      proposalsLimit: "10 / month",
      popular: false,
      cta: "Current Free Plan",
      features: [
        { title: "Up to 2 Active Service Listings", included: true },
        { title: "Standard Marketplace Discovery", included: true },
        { title: "Verified Student ID Badge", included: true },
        { title: "10 Community Proposals / month", included: true },
        { title: "Escrow Payment Vault Protection", included: true },
        { title: "Standard 5% Payout Platform Fee", included: false, detail: "5% fee deducted on payouts" },
        { title: "Custom Portfolio URL (/portfolio/you)", included: false },
        { title: "Featured Search Placement Boost", included: false },
        { title: "Unlimited Proposal Submissions", included: false },
        { title: "Instant UPI Direct Settlement", included: false },
        { title: "Campus Agency / Team Mode", included: false },
      ],
    },
    {
      id: "pro" as const,
      name: "Student Pro",
      badge: "Most Popular",
      tagline: "0% commission pass for active student freelancers and creators.",
      monthlyPrice: 149,
      yearlyMonthlyEquivalent: 99,
      yearlyTotalPrice: 1188,
      commissionRate: "0% (Keep 100%)",
      listingsLimit: "Unlimited",
      proposalsLimit: "Unlimited",
      popular: true,
      cta: "Upgrade to Pro",
      features: [
        { title: "Zero Commission (Keep 100% of Payouts)", included: true, highlight: true },
        { title: "Unlimited Active Service Listings", included: true },
        { title: "SkillSetu Pro Gold Badge", included: true },
        { title: "Unlimited Community Job Proposals", included: true },
        { title: "Custom Portfolio URL (/portfolio/yourname)", included: true },
        { title: "Featured Search Placement Boost", included: true },
        { title: "Instant UPI Direct Payout Settlement", included: true },
        { title: "Direct WhatsApp Client Alerts", included: true },
        { title: "24/7 Priority Dispute Support", included: true },
        { title: "Campus Agency / Team Mode", included: false },
        { title: "High-Budget Fest & Corporate RFPs", included: false },
      ],
    },
    {
      id: "agency" as const,
      name: "Campus Agency",
      badge: "For Teams & Clubs",
      tagline: "For student teams, fest committees, and multi-disciplinary collectives.",
      monthlyPrice: 399,
      yearlyMonthlyEquivalent: 299,
      yearlyTotalPrice: 3588,
      commissionRate: "0% (Keep 100%)",
      listingsLimit: "Unlimited",
      proposalsLimit: "Unlimited",
      popular: false,
      cta: "Get Campus Agency Pass",
      features: [
        { title: "Everything in Student Pro Plan", included: true },
        { title: "Zero Commission on All Team Payouts", included: true, highlight: true },
        { title: "Team Collaboration: Up to 5 Student Members", included: true, highlight: true },
        { title: "Exclusive High-Budget Fest & Corporate Gigs (> ₹15k)", included: true },
        { title: "Campus Agency Verified Badge", included: true },
        { title: "Custom Domain Support & PDF Resume Export", included: true },
        { title: "Dedicated Dispute Concierge", included: true },
        { title: "Priority Support & Dedicated Account Manager", included: true },
      ],
    },
  ],
  featureComparisonMatrix: [
    { feature: "Platform Commission on Payouts", free: "5% Fee", pro: "0% (Keep 100%)", agency: "0% (Keep 100%)", highlight: true },
    { feature: "Active Service Listings", free: "2 Maximum", pro: "Unlimited", agency: "Unlimited" },
    { feature: "Community Proposals per Month", free: "10 Proposals", pro: "Unlimited", agency: "Unlimited" },
    { feature: "Custom Portfolio Link", free: false, pro: "skillsetu.in/portfolio/you", agency: "Custom Domain + Link" },
    { feature: "Search & Category Placement", free: "Standard", pro: "⚡ 3x Search Boost", agency: "🌟 Top Placement" },
    { feature: "Team Mode & Collaborators", free: false, pro: false, agency: "Up to 5 Members" },
    { feature: "Instant UPI Settlement", free: "2-3 Days", pro: "⚡ Instant Payout", agency: "⚡ Instant Payout" },
    { feature: "High-Budget Fest / Corporate Leads", free: false, pro: "Standard", agency: "Exclusive Priority Access" },
    { feature: "Dispute & Payment Protection", free: "Standard", pro: "24/7 Priority", agency: "Dedicated Concierge" },
  ],
};
